### ISSUE TITLE
How use Accessor & Mutators?

### ISSUE THREAD

**Issue by riskihajar** [nazieb/elegant-orm#1]
I have following this instruction https://github.com/nazieb/elegant-orm/tree/02f55dd3e17fa9d70a1cd3cfbf4c2c7179198ee7#accessors-and-mutators
but when i try var_dump/print_r using toArray(); the attribute accessor not showing.

**Comment by nazieb** [comment]
Hi, can you provide some example of your code?

**Comment by riskihajar** [comment]
this my code

```
<?php
class SalonModel extends Elegant\Model {
    protected $table  = "salon";
    protected $primary = 'salon_id';

    function getAttrMapTitle($value, $model)
    {
        return date('d/m/y', strtotime($model->salon_open_start)). " - ".date('d/m/y', strtotime($model->salon_open_end)). " ".$model->salon_open_time;
    }
}
```

**Comment by nazieb** [comment]
Hi, sorry took awhile to look your issue. I've been busy recently.

Does the "maptitle" field really exist on the table "salon"? Or are you trying to make up an imaginary field based on the actual fields?

I see you didn't use the "$value" variable in the method, so I presume the field doesn't actually exist.

Right now the accessors only work if the field actually exists in the DB. I'll take a look how to support this kind of methods
